// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiData } from "./UiData";

/**
 * Static application identity plus the tables the UI needs.
 *
 * Serialize-only: `UiData` carries `FlagLabel` and `StoryPreset`, which hold
 * `'static` borrowed fields and so cannot be deserialised.
 */
export type AppInfo = { 
/**
 * Binary name.
 */
name: string, 
/**
 * Binary version.
 */
version: string, 
/**
 * `dw4core` version, so a stale binding is detectable.
 */
core_version: string, 
/**
 * Bytes in a save.
 */
save_size: number, 
/**
 * Bytes in one mirrored block.
 */
block_size: number, 
/**
 * Bumped whenever any payload changes shape.
 */
schema_version: number, 
/**
 * Static UI tables.
 */
ui: UiData, };
