// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A field's limits: what the game tolerates, and what the type can hold.
 */
export type Cap = { 
/**
 * Maximum accepted in Normal mode. Values are never negative there.
 */
normal_max: number, 
/**
 * Minimum accepted in Advanced mode.
 */
dtype_min: number, 
/**
 * Maximum accepted in Advanced mode.
 */
dtype_max: number, };
