// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The item category encoded in a base id's second byte.
 */
export type Category = "weapon" | "styled" | "core" | "board" | "mod" | "modequipped" | { "unknown": number };
