// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The save's difficulty. Normal is `SYSgetDifficulty() == -1`.
 */
export type Difficulty = "Normal" | "Hard" | "VeryHard";
