// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Difficulty } from "./Difficulty";

/**
 * Which difficulty's mirror set to write alongside a story edit.
 *
 * The save does not store its difficulty, so `Auto` asks the editor to infer
 * it (spec 4.5). This is the `difficulty_var` of the Python GUI, whose default
 * there is `"auto"`.
 */
export type DifficultyChoice = "auto" | { "fixed": Difficulty };
