// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifficultyChoice } from "./DifficultyChoice";
import type { Species } from "./Species";
import type { StoryEdit } from "./StoryEdit";

/**
 * Everything the UI can change, in one payload.
 *
 * Mirrors the Python `collect()` dictionary field-for-field, minus the raw
 * offset edits that DW4orge drops by design (spec 5.3).
 *
 * Two field groups are *not* plain values:
 *
 * - `weapons`, `armor` and `sub` are **indices into `device`**, exactly as the
 *   Python `_parse_equip` returns them.
 * - `wmods` and `amods` are **mod-chip base ids** (`None` = empty socket), not
 *   indices. The Python editor resolves them to indices during `collect()`,
 *   adding the chip to the device folder if absent; doing that at apply time
 *   instead means a socket cannot carry a stale index.
 */
export type EditSet = { 
/**
 * Species to switch to. Rewrites `DIGIMONNAME` when it changes.
 */
species: Species, 
/**
 * Player name, at most 3 fullwidth characters.
 */
name: string, 
/**
 * Currency.
 */
bit: number, 
/**
 * X-Data currency.
 */
xdata: number, 
/**
 * Junk-shop donation **threshold** (not a tier number), as `collect()`
 * writes `dict(JUNK_TIERS)[tier]`.
 */
junk: number, 
/**
 * Level for the edited species.
 */
level: number, 
/**
 * EXP for the edited species.
 */
exp: number, 
/**
 * The 9 technique values, signed.
 */
tech: [number, number, number, number, number, number, number, number, number], 
/**
 * The 11 X-Data power-up values.
 */
upcnt: [number, number, number, number, number, number, number, number, number, number, number], 
/**
 * The 30 usable device-folder slots.
 */
device: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], 
/**
 * 3 weapon slots, as indices into `device`.
 */
weapons: [number, number, number], 
/**
 * Armor slot, as an index into `device`.
 */
armor: number, 
/**
 * Sub/board slot, as an index into `device`.
 */
sub: number, 
/**
 * 5 weapon mod sockets, as mod-chip base ids.
 */
wmods: [number | null, number | null, number | null, number | null, number | null], 
/**
 * 5 armor mod sockets, as mod-chip base ids.
 */
amods: [number | null, number | null, number | null, number | null, number | null], 
/**
 * Story bits to write. Bits absent from this list keep their stored value.
 */
story: Array<StoryEdit>, 
/**
 * Which difficulty's mirrors to write for those story bits.
 */
difficulty: DifficultyChoice, 
/**
 * Bank balance.
 */
bank_bit: number, 
/**
 * The 12 owned disk counts.
 */
disks: [number, number, number, number, number, number, number, number, number, number, number, number], 
/**
 * The 96 bank item slots.
 *
 * A `Vec` rather than a 96-element array because serde only derives for
 * arrays up to 32 elements. It also matches `builder::SaveSpec::bank` and
 * `SaveData::get_raw_bank_slots`.
 */
bank_items: Array<number>, };
