// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * One problem with one field.
 *
 * `path` is the key the frontend uses to highlight the exact control:
 * `"bit"`, `"device[3].mods"`, `"equip.armor"`, `"story.flag[66]"`,
 * `"bank_items[7]"`.
 */
export type FieldError = { 
/**
 * Where the problem is.
 */
path: string, 
/**
 * What is wrong, in a form fit to show the user.
 */
message: string, 
/**
 * Whether this blocked the edit.
 */
severity: Severity, };
