// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A flag and the label the UI shows for it.
 */
export type FlagLabel = { 
/**
 * The flag index.
 */
flag: number, 
/**
 * Human label.
 */
label: string, };
