// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

/**
 * Anything an IPC call or a service call can fail with.
 *
 * Internally tagged because serde cannot internally tag a `Vec` variant.
 */
export type IpcError = { "kind": "validation", 
/**
 * The per-field reasons.
 */
fields: Array<FieldError>, } | { "kind": "core", 
/**
 * The `dw4core::Error` variant name.
 */
variant: string, 
/**
 * Its rendered message.
 */
message: string, } | { "kind": "no_open_document" } | { "kind": "unsupported", 
/**
 * Why not.
 */
message: string, };
