// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

/**
 * One catalogue entry, keyed by its base id (the low 16 bits of a stored id).
 */
export type Item = { 
/**
 * The base id: `category << 8 | index`.
 */
base_id: number, 
/**
 * Display name, without any grade suffix.
 */
name: string, 
/**
 * Which slot the item belongs to.
 */
category: Category, 
/**
 * Grade index 0-4, where the item is graded.
 */
grade: number | null, 
/**
 * Free-text caveat, where the data files carry one.
 */
note: string | null, };
