// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One active story flag and the mirror it is restored from, per difficulty.
 */
export type Mirror = { 
/**
 * The flag the game reads during play.
 */
active: number, 
/**
 * Where the active flag is copied from on Normal.
 */
normal: number, 
/**
 * Where the active flag is copied from on Hard.
 */
hard: number, 
/**
 * Where the active flag is copied from on Very Hard.
 */
very_hard: number, };
