// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cap } from "./Cap";

/**
 * One cap, keyed by the field path the validator uses.
 */
export type NamedCap = { 
/**
 * Validator path, e.g. `"bit"` or `"upcnt"`.
 */
field: string, 
/**
 * The limits themselves.
 */
cap: Cap, };
