// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifficultyChoice } from "./DifficultyChoice";
import type { Species } from "./Species";

/**
 * Everything the New Save dialog supplies.
 */
export type NewSaveRequest = { 
/**
 * Species for the new character.
 */
species: Species, 
/**
 * Player name, at most 3 fullwidth characters.
 */
name: string, 
/**
 * A `STORY_PRESETS` name, or `None` for a storyless save.
 */
story: string | null, 
/**
 * Which difficulty's mirror set to seed. `Auto` means Normal here; a
 * brand-new save has no live mirror set to infer from.
 */
difficulty: DifficultyChoice, };
