// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveView } from "./SaveView";
import type { SourceKind } from "./SourceKind";

/**
 * The result of opening or creating a save.
 */
export type OpenResult = { 
/**
 * The file, or `None` for a save that has not been written yet.
 */
path: string | null, 
/**
 * Which container it came from.
 */
source: SourceKind, 
/**
 * The projected fields.
 */
view: SaveView, };
