// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One power-up slot's Normal-mode limit.
 */
export type PowerupLimit = { 
/**
 * Slot index in `BASE_UPCNT` order.
 */
slot: number, 
/**
 * Display name.
 */
stat: string, 
/**
 * Largest value Normal mode accepts.
 */
normal_max: number, };
