// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One species' stored progression, for the Character section's species
 * selector.
 *
 * Mirrors the per-species half of `SaveView`, so switching species can show
 * that block's values without a `get_view` round-trip (`_load_species_stats`,
 * `save_editor_gui.py:776`). Response-only: nothing deserialises it.
 */
export type SpeciesStats = { 
/**
 * Level stored for this species.
 */
level: number, 
/**
 * EXP for this species, lifted to the level threshold in Normal mode.
 */
exp: number, 
/**
 * The 9 techniques, signed.
 */
tech: [number, number, number, number, number, number, number, number, number], 
/**
 * The 11 power-ups.
 */
upcnt: [number, number, number, number, number, number, number, number, number, number, number], };
