// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the 16 species. The discriminant **is** the species index.
 */
export type Species = "Agumon" | "Veemon" | "Girumon" | "Dorumon" | "WereGarurumon" | "HerculesKabuterimon" | "WarGreymon" | "AngelRimon" | "Beelzemon" | "Alphamon" | "BlackWarGreymon" | "ImperialdramonFm" | "ImperialdramonPm" | "MetalGarurumon" | "DukeCrimson" | "Susanoomon";
