// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A complete story state: which flags and folders to set.
 */
export type StoryPreset = { 
/**
 * Label shown in the preset dropdown.
 */
name: string, 
/**
 * Active flags to set.
 */
flags: Array<number>, 
/**
 * Folders to set.
 */
folders: Array<number>, };
