// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoryKind } from "./StoryKind";

/**
 * One story bit to write.
 *
 * Mirrors one entry of the Python `collect()` story dict, which is keyed by
 * `(kind, index)` and valued `0`/`1`.
 */
export type StoryEdit = { 
/**
 * Which field this targets.
 */
kind: StoryKind, 
/**
 * Flag index (0-1023) or folder index (0-11).
 */
index: number, 
/**
 * The value to write.
 */
value: boolean, };
