// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Difficulty } from "./Difficulty";
import type { StoryKind } from "./StoryKind";

/**
 * One story bit to write, and the difficulty it was edited on.
 *
 * Mirrors one entry of the Python `collect()` story dict, which is keyed by
 * `(kind, index)` and valued `0`/`1`. `difficulty` replaces the Python GUI's
 * single `difficulty_var`, so one save can carry edits made on several
 * difficulties at once.
 */
export type StoryEdit = { 
/**
 * Which field this targets.
 */
kind: StoryKind, 
/**
 * Flag index (0-1023) or folder index (0-11).
 */
index: number, 
/**
 * The value to write.
 */
value: boolean, 
/**
 * The difficulty whose mirror column this edit targets, and every lower
 * one. The live bytes are written either way.
 */
difficulty: Difficulty, };
