// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two story fields an edit targets.
 */
export type StoryKind = "flag" | "folder";
