// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlagLabel } from "./FlagLabel";
import type { Item } from "./Item";
import type { Mirror } from "./Mirror";
import type { NamedCap } from "./NamedCap";
import type { PowerupLimit } from "./PowerupLimit";
import type { StoryPreset } from "./StoryPreset";

/**
 * Static tables, fetched once at startup so no keystroke costs a round-trip.
 *
 * Serialize-only for the same reason as [`AppInfo`].
 */
export type UiData = { 
/**
 * Every catalogue entry, ordered by base id.
 */
catalogue: Array<Item>, 
/**
 * Field limits, keyed by the path `validate` reports.
 */
caps: Array<NamedCap>, 
/**
 * The eleven power-up slots and their Normal-mode caps.
 */
powerups: Array<PowerupLimit>, 
/**
 * The active-to-mirror table.
 */
mirrors: Array<Mirror>, 
/**
 * The twelve story folder labels.
 */
folder_labels: Array<string>, 
/**
 * Flag labels for every story group.
 */
flag_labels: Array<FlagLabel>, 
/**
 * The story presets.
 */
story_presets: Array<StoryPreset>, };
