#!/usr/bin/env python3
"""Regenerate dw4core's golden fixtures from the reverse-engineering tree.

Reads (never writes) Decomp/DW4/DW4_Save_Editor and its memcard dumps, using the
Python editor as the oracle: whatever dw4save.py reads from the real card is what
the Rust core must reproduce.

The editor's venv/bin/python symlink is broken (it points at a nonexistent
/usr/bin/python), so this script does not use it. It puts the venv's
site-packages on sys.path and runs under any Python 3.8+.

    python3 tools/gen_fixtures.py --decomp /workspace/Decomp/DW4

Run it by hand when the format changes; commit the result.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
OUT = REPO / "crates/dw4core/tests/fixtures/mcd001"

# The real card, and the save inside it, as expected.json's provenance records.
CARD = "memcards/Mcd001.ps2"


def import_reference(decomp: Path):
    """Import dw4save from the read-only Decomp tree."""
    editor = decomp / "DW4_Save_Editor"
    venvs = sorted((editor / "venv/lib").glob("python3.*/site-packages"))
    if not venvs:
        sys.exit(f"no site-packages under {editor}/venv/lib - is the venv present?")
    for path in (str(venvs[0]), str(editor)):
        if path not in sys.path:
            sys.path.insert(0, path)
    import dw4save  # noqa: E402

    return dw4save


def dump(d, save) -> dict:
    """Everything the Rust core must reproduce, read through the Python oracle."""
    species = save.detect_species()
    nicknames = {}
    for i in range(d.DEVICE_SAVE_SLOTS):
        fid = save.device(i)
        if fid != d.EMPTY:
            base = fid & 0xFFFF
            item = d.get_catalogue().get(base)
            nicknames[str(base)] = item.name if item else f"[invalid] 0x{base:04x}"
    return {
        "verify": save.verify(),
        "checksum_block": save.get_u32(0, 0),
        "version": save.version,
        "isuse": save.get_u32(0x08, 0),
        "unique": save.get_u32(0x0C, 0),
        "digimon_name": save.digimon_name,
        "player_name": save.player_name,
        "detected_species": species,
        "bit": save.bit,
        "xdata": save.xdata,
        "menu_level": save.menu_level,
        "junk_counter": save.junk_counter,
        "device": [save.device(i) for i in range(d.DEVICE_SAVE_SLOTS)],
        "weapon": [save.weapon(i) for i in range(3)],
        "weapon_mod": [save.wmod(i) for i in range(5)],
        "armor": save.armor(),
        "armor_mod": [save.amod(i) for i in range(5)],
        "sub": save.sub(),
        "disk": [save.disk_count(i) for i in range(12)],
        "bank_bit": save.bank_bit,
        "bank_device": [save.bank_device(i) for i in range(d.BANK_SLOTS)],
        "base_level": [save.level(i) for i in range(16)],
        "base_exp": [save.exp(i) for i in range(16)],
        "base_skill_active": [save.skill(i, species) for i in range(9)],
        "base_upcnt_active": [save.upcnt(i, species) for i in range(11)],
        "nicknames": nicknames,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--decomp", default="/workspace/Decomp/DW4")
    args = ap.parse_args()
    decomp = Path(args.decomp).resolve()

    d = import_reference(decomp)
    card = decomp / CARD
    save = d.load_any(str(card))

    OUT.mkdir(parents=True, exist_ok=True)

    # The raw save, extracted through the oracle, is the fixture itself.
    (OUT / "save.raw").write_bytes(bytes(save.raw))

    expected = dump(d, save)
    (OUT / "expected.json").write_text(json.dumps(expected, indent=2) + "\n")

    (OUT.parent / "PROVENANCE.md").write_text(
        "# Fixture provenance\n\n"
        "Generated by `tools/gen_fixtures.py`. Do not edit by hand.\n\n"
        "| Item | Source |\n| --- | --- |\n"
        f"| `mcd001/save.raw` | `{CARD}` -> `BASLUS-20836savedata/BASLUS-20836savedata`, "
        "extracted with the Python editor's `dw4save.load_any` |\n"
        "| `mcd001/expected.json` | values read by the same module |\n\n"
        "The Python editor in `Decomp/DW4/DW4_Save_Editor` is the only known-good\n"
        "implementation; these fixtures freeze its reading of a real save so the Rust\n"
        "core can be tested without Python.\n"
    )

    n = len(bytes(save.raw))
    print(f"wrote {OUT}/save.raw ({n} bytes), expected.json, and PROVENANCE.md")
    assert n == 81920, f"expected an 81920-byte save, got {n}"
    assert expected["verify"], "the oracle says the checksum does not verify"


if __name__ == "__main__":
    main()
